export const SUBMITDATA="SUBMITDATA";
export const DASHBOARDDATA="DASHBOARDDATA";
export const DISPLAYDATA="DISPLAYDATA";
export const ALLPRODUCTDATA="ALLPRODUCTDATA";
export const CARTDETAILS="CARTDETAILS";
export const CARTPRODUCT="CARTPRODUCT";
export const PLACEORDER="PLACEORDER";
export const CONFIRMPLACEORDER="CONFIRMPLACEORDER";